#! /bin/sh

#########################################################3

#	Configuracion del entorno de linux (Dis Arch)

#########################################################
#Configuracion de resolucion
xrandr --output HDM1-1 --primary --mode 1920x1080 --rotate normal &

#Background
feh --bg-fill $HOME/.local/share/background/lofi.jpg &

#Quitar el Mouse con forma de X
xsetroot -cursor_name left_ptr &

#Configuracion de trasparencia
picom --experimental-backends &

#Evitar bloqueo de teclado numerico
numlockx on &

#Taskbar tint2
pkill tint2
tint2 &
sleep 0.1 &&
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2)

#Gestor de red 
pkill nm-applet
nm-applet &

#Notoficaciones
pkill xfce4-notifyd
/usr/lib/xfce4/notifyd/xfce4-notifyd &

#Volumen
volumeicon &

#######################################################

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V  


#Configuracion de las ventanas 

bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true
bspc config focus_follows_pointer       true
bspc config top_padding  0
bspc config bottom_padding 25
bspc config right_padding 0
bspc config left_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
